steps:
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - --no-cache
      - -t
      - $_AR_HOSTNAME/$PROJECT_ID/gce-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - -f
      - Dockerfile
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/gce-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - name: gcr.io/cloud-builders/gcloud
    id: Delete old
    allowFailure: true
    args:
      - compute
      - instances
      - delete
      - $_SERVICE_NAME-machine
      - --zone=$_REGION-$_ZONE
      - -q
  - name: gcr.io/cloud-builders/gcloud
    id: Get bot token
    entrypoint: bash
    args:
      - -c
      - |
        BOT_TOKEN=$(gcloud secrets versions access latest --secret="tg-bot-token")
        echo $$BOT_TOKEN
    dir: .
    secretEnv:
      - BOT_TOKEN
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy
    args:
      - beta
      - compute
      - instances
      - create-with-container
      - $_SERVICE_NAME-machine
      - --zone=$_REGION-$_ZONE
      - --container-stdin
      - --container-tty
      - --container-image=$_AR_HOSTNAME/$PROJECT_ID/gce-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --machine-type=$_MACHINE_TYPE
      - --labels=commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,branch=$_BRANCH_NAME
      - --container-env=BOT_TOKEN=${_BOT_TOKEN}
images:
  - $_AR_HOSTNAME/$PROJECT_ID/gce-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _REGION: us-central1
  _ZONE: a
  _SERVICE_NAME: txt2gpx
  _MACHINE_TYPE: e2-micro
  _BRANCH_NAME: ${BRANCH_NAME//\//_}
tags:
  - txt2gpx_$_BRANCH_NAME
