apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "txt2gpx"
  namespace: "default"
  labels:
    app: "txt2gpx"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "txt2gpx"
  template:
    metadata:
      labels:
        app: "txt2gpx"
    spec:
      containers:
        - name: "txt2gpx-sha256-1"
          image: "${IMAGE}"
